name: pipelines

on:
  push:
    branches: [ "main" ]

jobs:
  build-docker-image:
    name: BuildDockerImage
    runs-on: ubuntu-20.04
    steps:
      - name: Build And Push Image to Docker registry
        uses: actions/checkout@v3
      - run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build . --file Dockerfile --tag iamta/wallet-monitioring-api-prod:latest
          docker push iamta/wallet-monitioring-api-prod:latest